stages:
  - build
  - deploy

build:docker:image:
  stage: build
  image: docker:stable
  dependencies: []  #don't depend on explicit artifacts from any previous job
  # tags:
  #   - docker-build-cache
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build -f ./devops/docker/Dockerfile -t $DOCKER_REGISTRY_PROJECT_PATH:latest -t $DOCKER_REGISTRY_PROJECT_PATH:$PACKAGE_VERSION .
    - docker push $DOCKER_REGISTRY_PROJECT_PATH:$PACKAGE_VERSION
    - docker push $DOCKER_REGISTRY_PROJECT_PATH:latest

deploy:kubernetes:
  stage: deploy
  retry: 1
  image: dtzar/helm-kubectl:3.1.2
  before_script:
    - apk add --update libintl && apk add --virtual build_deps gettext git && cp /usr/bin/envsubst /usr/local/bin/envsubst
  script:
    - sh devops/helm/scripts/set_k8s_context.sh
    - sh devops/helm/scripts/helm-deploy.sh