apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logging-db.fullname" . }}
  labels:
    app: {{ include "logging-db.name" . }}
    chart: {{ include "logging-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "logging-db.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "logging-db.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: MYSQL_DBNAME
              value: {{ .Values.image.dbname }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.image.dbpassword }}
            - name: MYSQL_USERNAME
              value: {{ .Values.image.dbusername }}
            - name: MYSQL_HOST
              value: {{ .Values.image.dbhost }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}